mappings:
  SilverstripeColumnsPageControllerExtension: Sunnysideup\Columns\Control\SilverstripeColumnsPageControllerExtension
  SilverstripeColumnsPageExtension: Sunnysideup\Columns\Model\SilverstripeColumnsPageExtension
